// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from '@prismicio/client';

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

/**
 * Content for Projeto documents
 */
interface TesteDocumentData {
  /**
   * Titulo field in *Projeto*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: teste.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Descricao field in *Projeto*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: teste.description
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  description: prismic.KeyTextField;

  /**
   * Tipo field in *Projeto*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: teste.type
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  type: prismic.KeyTextField;

  /**
   * Projeto online field in *Projeto*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: teste.link
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;

  /**
   * Thumbnail field in *Projeto*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: teste.thumbnail
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  thumbnail: prismic.ImageField<never>;
}

/**
 * Projeto document from Prismic
 *
 * - **API ID**: `teste`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type TesteDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<TesteDocumentData>, 'teste', Lang>;

export type AllDocumentTypes = TesteDocument;

/**
 * Primary content in *Projeto2 → Default → Primary*
 */
export interface Projeto2SliceDefaultPrimary {
  /**
   * Title field in *Projeto2 → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: projeto2.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Description field in *Projeto2 → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: projeto2.default.primary.description
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  description: prismic.KeyTextField;
}

/**
 * Default variation for Projeto2 Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type Projeto2SliceDefault = prismic.SharedSliceVariation<
  'default',
  Simplify<Projeto2SliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Projeto2*
 */
type Projeto2SliceVariation = Projeto2SliceDefault;

/**
 * Projeto2 Shared Slice
 *
 * - **API ID**: `projeto2`
 * - **Description**: Projeto2
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type Projeto2Slice = prismic.SharedSlice<
  'projeto2',
  Projeto2SliceVariation
>;

declare module '@prismicio/client' {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig
    ): prismic.Client<AllDocumentTypes>;
  }

  interface CreateWriteClient {
    (
      repositoryNameOrEndpoint: string,
      options: prismic.WriteClientConfig
    ): prismic.WriteClient<AllDocumentTypes>;
  }

  interface CreateMigration {
    (): prismic.Migration<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      TesteDocument,
      TesteDocumentData,
      AllDocumentTypes,
      Projeto2Slice,
      Projeto2SliceDefaultPrimary,
      Projeto2SliceVariation,
      Projeto2SliceDefault
    };
  }
}
