// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismicT from "@prismicio/types";
import type * as prismic from "@prismicio/client";

type Simplify<T> = {
    [KeyType in keyof T]: T[KeyType];
};
/** Content for Projeto documents */
interface TesteDocumentData {
    /**
     * Titulo field in *Projeto*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: teste.title
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    title: prismicT.KeyTextField;
    /**
     * Descricao field in *Projeto*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: teste.description
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    description: prismicT.KeyTextField;
    /**
     * Tipo field in *Projeto*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: teste.type
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    type: prismicT.KeyTextField;
    /**
     * Projeto online field in *Projeto*
     *
     * - **Field Type**: Link
     * - **Placeholder**: *None*
     * - **API ID Path**: teste.link
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
     *
     */
    link: prismicT.LinkField;
    /**
     * Thumbnail field in *Projeto*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: teste.thumbnail
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/image
     *
     */
    thumbnail: prismicT.ImageField<never>;
}
/**
 * Projeto document from Prismic
 *
 * - **API ID**: `teste`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type TesteDocument<Lang extends string = string> = prismicT.PrismicDocumentWithUID<Simplify<TesteDocumentData>, "teste", Lang>;
export type AllDocumentTypes = TesteDocument;
/**
 * Primary content in Projeto1 → Primary
 *
 */
interface Projeto1SliceDefaultPrimary {
    /**
     * Title field in *Projeto1 → Primary*
     *
     * - **Field Type**: Title
     * - **Placeholder**: This is where it all begins...
     * - **API ID Path**: projeto1.primary.title
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    title: prismicT.TitleField;
    /**
     * Description field in *Projeto1 → Primary*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: A nice description of your feature
     * - **API ID Path**: projeto1.primary.description
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    description: prismicT.RichTextField;
}
/**
 * Default variation for Projeto1 Slice
 *
 * - **API ID**: `default`
 * - **Description**: `Projeto1`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type Projeto1SliceDefault = prismicT.SharedSliceVariation<"default", Simplify<Projeto1SliceDefaultPrimary>, never>;
/**
 * Slice variation for *Projeto1*
 *
 */
type Projeto1SliceVariation = Projeto1SliceDefault;
/**
 * Projeto1 Shared Slice
 *
 * - **API ID**: `projeto1`
 * - **Description**: `Projeto1`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type Projeto1Slice = prismicT.SharedSlice<"projeto1", Projeto1SliceVariation>;
declare module "@prismicio/client" {
    interface CreateClient {
        (repositoryNameOrEndpoint: string, options?: prismic.ClientConfig): prismic.Client<AllDocumentTypes>;
    }
    namespace Content {
        export type { TesteDocumentData, TesteDocument, AllDocumentTypes, Projeto1SliceDefaultPrimary, Projeto1SliceDefault, Projeto1SliceVariation, Projeto1Slice };
    }
}
